Update LogUtils.java
aliyun/aliyun-openapi-java-sdk pull request #529
Opened 2020-12-15 13:28 UTC by shencangsheng

优化时区部分重复代码

2020-12-15 13:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aliyun/aliyun-openapi-java-sdk?pullRequest=529) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aliyun/aliyun-openapi-java-sdk?pullRequest=529) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aliyun/aliyun-openapi-java-sdk?pullRequest=529) it.</sub>

2020-12-23 07:45 UTC, JacksonTian requested changes
SMC

2020-12-23 07:45 UTC, JacksonTian commented on aliyun-java-sdk-core/src/main/java/com/aliyuncs/utils/LogUtils.java
> +        formatLocaleNow(TimeZone.getTimeZone("UTC"));
没有 return

2020-12-23 08:00 UTC, shencangsheng commented on aliyun-java-sdk-core/src/main/java/com/aliyuncs/utils/LogUtils.java
> +        formatLocaleNow(TimeZone.getTimeZone("UTC"));
@JacksonTian  已修改

2020-12-28 10:27 UTC, shencangsheng commented
已签署开源协议 @JacksonTian

2021-01-11 03:46 UTC, JacksonTian approved these changes

2021-01-11 03:46 UTC, merged

2021-01-11 03:46 UTC, JacksonTian commented
Thanks @shencangsheng